"""empty message

Revision ID: 0593e93dc3f8
Revises: 
Create Date: 2020-06-11 19:30:47.228199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0593e93dc3f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_invitations', sa.Column('email', sa.Unicode(length=255), nullable=True))
    op.add_column('user_invitations', sa.Column('first_name', sa.Unicode(length=50), nullable=True))
    op.add_column('user_invitations', sa.Column('last_name', sa.Unicode(length=50), nullable=True))
    op.add_column('user_invitations', sa.Column('mobile_phone', sa.String(length=15), nullable=True))
    op.create_unique_constraint(None, 'user_invitations', ['email'])
    op.drop_column('user_invitations', 'login')
    op.alter_column('users', 'is_bulk_invite',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_bulk_invite',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('user_invitations', sa.Column('login', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_invitations', type_='unique')
    op.drop_column('user_invitations', 'mobile_phone')
    op.drop_column('user_invitations', 'last_name')
    op.drop_column('user_invitations', 'first_name')
    op.drop_column('user_invitations', 'email')
    # ### end Alembic commands ###
