"""empty message

Revision ID: 87aa6288cb1b
Revises: fab290c496ef
Create Date: 2019-08-22 22:13:28.102455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87aa6288cb1b'
down_revision = 'fab290c496ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'prayer_requests_by_email',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'prayer_requests_by_sms',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'private_messages_by_sms',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'private_messages_by_email',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'private_messages_by_email',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'private_messages_by_sms',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'prayer_requests_by_sms',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'prayer_requests_by_email',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
