"""empty message

Revision ID: 889a1777d874
Revises: 086c6c032c40
Create Date: 2020-07-05 21:13:44.809412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '889a1777d874'
down_revision = '086c6c032c40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_invitations', sa.Column('invite_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_invitations', 'invite_count')
    # ### end Alembic commands ###
