"""empty message

Revision ID: 929224607db7
Revises: ef1228526a90
Create Date: 2019-08-25 23:23:20.758914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929224607db7'
down_revision = 'ef1228526a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('login_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'login_count')
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###
