"""empty message

Revision ID: 96181d4a2ba0
Revises: c55c3f4958c0
Create Date: 2019-08-22 08:07:32.278390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96181d4a2ba0'
down_revision = 'c55c3f4958c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invited_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['invited_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'invited_by')
    # ### end Alembic commands ###
