"""empty message

Revision ID: fab290c496ef
Revises: f320e378eab0
Create Date: 2019-08-22 22:12:38.844438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fab290c496ef'
down_revision = 'f320e378eab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('prayer_requests_by_email', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('prayer_requests_by_sms', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('private_messages_by_sms', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('private_messages_by_email', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'private_messages_by_email')
    op.drop_column('users', 'private_messages_by_sms')
    op.drop_column('users', 'prayer_requests_by_sms')
    op.drop_column('users', 'prayer_requests_by_email')
    # ### end Alembic commands ###
